// products-data.js - Data produk untuk halaman utama
window.productData = {
  // Data untuk kategori tabs
  categories: [
    { id: 0, name: "Semua Produk" },
    { id: 1, name: "Streaming" },
    { id: 2, name: "Musik" },
    { id: 3, name: "Editing" },
    { id: 4, name: "AI" }
  ],
  
  // Data produk
  products: [
    // 🔥 STREAMING
    {
      id: 1,
      name: "Netflix Premium",
      category: "Streaming",
      price: 25000,
      originalPrice: 49000,
      image: "../image/netflix.png",
      discount: 59,
      isPopular: true,
      isFlashSale: true,
      pageUrl: "pages/product.html?product=Netflix",
      description: "Layanan streaming film dan series terpopuler",
      features: ["Aktif Instan", "Garansi 30 Hari", "Support 24/7"],
      stock: 100,
      sold: 2500
    },
    {
      id: 2,
      name: "Vidio Premium",
      category: "Streaming",
      price: 25000,
      originalPrice: 35000,
      image: "../image/vidio.png",
      discount: 43,
      isPopular: false,
      isFlashSale: true,
      pageUrl: "pages/product.html?product=Vidio",
      description: "Streaming film dan series lokal terbaik",
      features: ["Aktif Instan", "Garansi 30 Hari", "Content Lokal"],
      stock: 80,
      sold: 1800
    },
    {
      id: 3,
      name: "Disney+ Hotstar",
      category: "Streaming",
      price: 28000,
      originalPrice: 55000,
      image: "../image/disneyplus.png",
      discount: 58,
      isPopular: false,
      isFlashSale: false,
      pageUrl: "pages/product.html?product=Disney",
      description: "Disney, Marvel, Star Wars dalam satu platform",
      features: ["Aktif Instan", "Garansi 30 Hari", "All Content"],
      stock: 60,
      sold: 1200
    },
    {
      id: 4,
      name: "YouTube Premium",
      category: "Streaming",
      price: 3500,
      originalPrice: 65000,
      image: "../image/youtube.png",
      discount: 95,
      isPopular: true,
      isFlashSale: true,
      pageUrl: "pages/product.html?product=Youtube",
      description: "YouTube Premium tanpa iklan",
      features: ["No Ads", "Background Play", "Download Video"],
      stock: 200,
      sold: 3500
    },
    {
      id: 5,
      name: "Amazon Prime Video",
      category: "Streaming",
      price: 11500,
      originalPrice: 12000,
      image: "../image/prime-video.png",
      discount: 46,
      isPopular: false,
      isFlashSale: true,
      pageUrl: "pages/product.html?product=Amazon Prime",
      description: "Amazon Prime Video dengan konten eksklusif",
      features: ["Aktif Instan", "Garansi 30 Hari", "Original Content"],
      stock: 0,
      sold: 800
    },
    {
      id: 6,
      name: "iQIYI Premium",
      category: "Streaming",
      price: 19000,
      originalPrice: 25000,
      image: "../image/iqiyi.png",
      discount: 44,
      isPopular: false,
      isFlashSale: false,
      pageUrl: "pages/product.html?product=Iqiyi",
      description: "Streaming drama dan film Asia",
      features: ["Aktif Instan", "Garansi 30 Hari", "Asian Content"],
      stock: 0,
      sold: 600
    },
    {
      id: 7,
      name: "Dramabox Premium",
      category: "Streaming",
      price: 23000,
      originalPrice: 30000,
      image: "../image/dramabox.png",
      discount: 40,
      isPopular: false,
      isFlashSale: false,
      pageUrl: "pages/product.html?product=Dramabox",
      description: "Platform streaming khusus drama",
      features: ["Aktif Instan", "Garansi 30 Hari", "Drama Collection"],
      stock: 30,
      sold: 450
    },
    {
      id: 8,
      name: "Loklok Premium",
      category: "Streaming",
      price: 26000,
      originalPrice: 45000,
      image: "../image/loklok.png",
      discount: 53,
      isPopular: false,
      isFlashSale: false,
      pageUrl: "pages/product.html?product=Loklok",
      description: "Streaming film pendek dan konten viral",
      features: ["Aktif Instan", "Garansi 30 Hari", "Short Videos"],
      stock: 35,
      sold: 500
    },
    {
      id: 9,
      name: "Viu Premium",
      category: "Streaming",
      price: 8250,
      originalPrice: 10000,
      image: "../image/viu.png",
      discount: 48,
      isPopular: false,
      isFlashSale: false,
      pageUrl: "pages/product.html?product=Viu",
      description: "Streaming drama Korea dan Asia",
      features: ["Aktif Instan", "No Ads", "Download Feature"],
      stock: 70,
      sold: 1500
    },
    {
      id: 10,
      name: "HBO Go",
      category: "Streaming",
      price: 20500,
      originalPrice: 50000,
      image: "../image/hbo-go.png",
      discount: 69,
      isPopular: false,
      isFlashSale: false,
      pageUrl: "pages/product.html?product=Hbo Go",
      description: "HBO dengan series premium",
      features: ["Aktif Instan", "Garansi 30 Hari", "Premium Series"],
      stock: 25,
      sold: 400
    },
    {
      id: 11,
      name: "WeTV VIP",
      category: "Streaming",
      price: 16500,
      originalPrice: 30000,
      image: "../image/wetv.png",
      discount: 62,
      isPopular: false,
      isFlashSale: false,
      pageUrl: "pages/product.html?product=Wetv",
      description: "Tencent Video international",
      features: ["Aktif Instan", "Garansi 30 Hari", "Chinese Content"],
      stock: 45,
      sold: 700
    },
    {
      id: 12,
      name: "HBO Max",
      category: "Streaming",
      price: 19500,
      originalPrice: 25000,
      image: "../image/hbo-go-max-com.png",
      discount: 42,
      isPopular: false,
      isFlashSale: false,
      pageUrl: "pages/product.html?product=Hbo Go Max",
      description: "HBO Max dengan konten lengkap",
      features: ["Aktif Instan", "Garansi 30 Hari", "Max Content"],
      stock: 0,
      sold: 300
    },
    {
      id: 13,
      name: "Bstation Premium",
      category: "Streaming",
      price: 11000,
      originalPrice: 35000,
      image: "../image/bstation.png",
      discount: 83,
      isPopular: true,
      isFlashSale: true,
      pageUrl: "pages/product.html?product=Bstation",
      description: "Platform streaming anime dan manga",
      features: ["Aktif Instan", "Garansi 30 Hari", "Anime Content"],
      stock: 55,
      sold: 900
    },
    {
      id: 14,
      name: "Youkou VIP",
      category: "Streaming",
      price: 15000,
      originalPrice: 30000,
      image: "../image/youkou.png",
      discount: 67,
      isPopular: false,
      isFlashSale: false,
      pageUrl: "pages/product.html?product=Youkou",
      description: "Youku dengan konten China terbaru",
      features: ["Aktif Instan", "Garansi 30 Hari", "Chinese Drama"],
      stock: 40,
      sold: 650
    },
    {
      id: 26,
      name: "Crunchyroll Premium",
      category: "Streaming",
      price: 13500,
      originalPrice: 30000,
      image: "../image/crunchyroll.png",
      discount: 65,
      isPopular: true,
      isFlashSale: true,
      pageUrl: "pages/product.html?product=Crunchyroll",
      description: "Streaming anime terbesar dengan koleksi terlengkap",
      features: ["Aktif Instan", "No Ads", "Simulcast", "Offline Viewing"],
      stock: 65,
      sold: 850
    },

    // 🔥 MUSIK
    {
      id: 15,
      name: "Spotify Premium",
      category: "Musik",
      price: 26000,
      originalPrice: 75000,
      image: "../image/spotify.png",
      discount: 72,
      isPopular: true,
      isFlashSale: false,
      pageUrl: "pages/product.html?product=Spotify",
      description: "Spotify Premium dengan fitur lengkap",
      features: ["No Ads", "Download Music", "High Quality"],
      stock: 0,
      sold: 2800
    },
    {
      id: 25,
      name: "Apple Music",
      category: "Musik",
      price: 8000,
      originalPrice: 20000,
      image: "../image/applemusic.png",
      discount: 75,
      isPopular: false,
      isFlashSale: false,
      pageUrl: "pages/product.html?product=Apple Music",
      description: "Apple Music dengan jutaan lagu",
      features: ["No Ads", "Download Songs", "High Quality Audio"],
      stock: 0,
      sold: 1600
    },

    // 🔥 EDITING
    {
      id: 16,
      name: "Canva Pro",
      category: "Editing",
      price: 2000,
      originalPrice: 20000,
      image: "../image/canva.png",
      discount: 90,
      isPopular: true,
      isFlashSale: true,
      pageUrl: "pages/product.html?product=Canva",
      description: "Canva Pro untuk desain grafis dengan semua elemen premium",
      features: ["All Elements", "Premium Templates", "No Watermark", "Background Remover"],
      stock: 200,
      sold: 4200
    },
    {
      id: 17,
      name: "Capcut Pro",
      category: "Editing",
      price: 1300,
      originalPrice: 10000,
      image: "../image/capcut.png",
      discount: 87,
      isPopular: true,
      isFlashSale: true,
      pageUrl: "pages/product.html?product=Capcut",
      description: "Capcut Pro untuk editing video tanpa watermark",
      features: ["No Watermark", "All Effects", "Premium Features", "Cloud Storage"],
      stock: 150,
      sold: 2200
    },
    {
      id: 18,
      name: "Remini Pro",
      category: "Editing",
      price: 13000,
      originalPrice: 20000,
      image: "../image/remini.png",
      discount: 60,
      isPopular: false,
      isFlashSale: false,
      pageUrl: "pages/product.html?product=Remini",
      description: "Remini untuk enhacement foto",
      features: ["AI Enhancement", "HD Quality", "All Features"],
      stock: 80,
      sold: 1400
    },
    {
      id: 19,
      name: "Meitu VIP",
      category: "Editing",
      price: 33000,
      originalPrice: 55000,
      image: "../image/meitu.png",
      discount: 49,
      isPopular: false,
      isFlashSale: false,
      pageUrl: "pages/product.html?product=Meitu",
      description: "Meitu untuk editing foto profesional",
      features: ["All Filters", "Premium Tools", "No Watermark"],
      stock: 60,
      sold: 1100
    },
    {
      id: 20,
      name: "Picsart Gold",
      category: "Editing",
      price: 8000,
      originalPrice: 15000,
      image: "../image/picsart.png",
      discount: 70,
      isPopular: false,
      isFlashSale: false,
      pageUrl: "pages/product.html?product=Picsart",
      description: "Picsart Gold untuk editing lengkap",
      features: ["All Stickers", "Premium Filters", "No Ads"],
      stock: 100,
      sold: 1800
    },
    {
      id: 21,
      name: "Ibis Paint X Pro",
      category: "Editing",
      price: 23000,
      originalPrice: 50000,
      image: "../image/ibispaint.png",
      discount: 64,
      isPopular: false,
      isFlashSale: false,
      pageUrl: "pages/product.html?product=Ibis Paint X",
      description: "Ibis Paint X untuk digital art",
      features: ["All Brushes", "Premium Tools", "No Ads"],
      stock: 0,
      sold: 900
    },
    {
      id: 22,
      name: "Alight Motion Pro",
      category: "Editing",
      price: 3500,
      originalPrice: 15000,
      image: "../image/alight-motion.png",
      discount: 67,
      isPopular: true,
      isFlashSale: true,
      pageUrl: "pages/product.html?product=Alight Motion",
      description: "Alight Motion Pro untuk motion graphics",
      features: ["All Effects", "Premium Tools", "No Watermark"],
      stock: 180,
      sold: 3500
    },
    {
      id: 27,
      name: "Dazzcam Pro",
      category: "Editing",
      price: 17000,
      originalPrice: 30000,
      image: "../image/dazzcam.png",
      discount: 57,
      isPopular: false,
      isFlashSale: false,
      pageUrl: "pages/product.html?product=Dazzcam",
      description: "Dazzcam untuk editing foto dengan efek vintage",
      features: ["Lifetime Access", "All Filters", "No Watermark", "Premium Effects"],
      stock: 45,
      sold: 620
    },

    // 🔥 AI
    {
      id: 28,
      name: "ChatGPT Plus",
      category: "AI",
      price: 13000,
      originalPrice: 60000,
      image: "../image/chatgpt.png",
      discount: 83,
      isPopular: true,
      isFlashSale: true,
      pageUrl: "pages/product.html?product=ChatGPT",
      description: "ChatGPT dengan akses premium untuk kebutuhan AI",
      features: ["GPT-4 Access", "No Limits", "Priority Support", "Plugins"],
      stock: 90,
      sold: 1200
    }
  ]
};

console.log("✅ products-data.js berhasil dimuat!");
console.log("Total produk:", window.productData.products.length);
console.log("✅ Semua harga telah DISINKRONKAN dengan produk terbaru");
console.log("✅ Produk baru ditambahkan: Crunchyroll, Dazzcam Pro, ChatGPT Plus");
console.log("✅ Flash sale dan produk populer telah diperbarui:");
console.log("   - Flash Sale: Netflix Premium, Vidio Premium, Youtube Premium, Amazon Prime Video, Bstation Premium, Canva Pro, Capcut Pro, Alight Motion Pro, Crunchyroll Premium, ChatGPT Plus");
console.log("   - Produk Populer: Netflix Premium, Youtube Premium, Bstation Premium, Spotify Premium, Canva Pro, Capcut Pro, Alight Motion Pro, Crunchyroll Premium, ChatGPT Plus");
console.log("Produk habis:", window.productData.products.filter(p => p.stock <= 0).map(p => p.name).join(", "));
console.log("Produk tersedia:", window.productData.products.filter(p => p.stock > 0).map(p => p.name).join(", "));
